# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='predicted_delivery_date',
        ),
        migrations.AddField(
            model_name='rent',
            name='numberOfRentalDays',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
