# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar_app', '0002_auto_20160719_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='real_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
